### PR TITLE
Support PHP 8

### PR DESCRIPTION
**Pull request by Naktibalda**
* Support PHP 8
* CI using Github Actions

### CODE REVIEW

**Comment by Naktibalda** [comment]
CI is working in my fork: https://github.com/Naktibalda/php-value-mask/runs/1486334228?check_suite_focus=true

**Comment by Naktibalda** [comment]
@Messere Are you going to merge this MR anytime soon?

**Comment by Messere** [comment]
@Naktibalda, yes, sorry that I kept you waiting and thanks for your pull request. 

I've just merged it and new version is already available from packagist.

**Comment by Naktibalda** [comment]
Thank you.

**Pull request merged**
